---
- name: update HTML files from templates
  hosts: localhost
  gather_facts: true
  vars:
    current_race_name: "Melons 24h"
    qual_hour: 13 #integer, dont quote, GMT
    qual_min: "30" #string to keep any leading zeros, in quotes
    race_hour: 14 #integer, dont quote, GMT
    race_min: "00" #string to keep any leading zeros, in quotes
    qual_start_gmt: "{{ qual_hour }}:{{ qual_min }}"
    race_start_gmt: "{{ race_hour }}:{{ race_min }}"
    qual_start_bst: "{{ qual_hour +1 }}:{{ qual_min }}"
    race_start_bst: "{{ race_hour +1 }}:{{ race_min }}"
    hatracer: true
    matstace: true
    jjwolf36: true
  tasks:
    - name: template 2 versions
      template:
        src: "index_{{ item }}.html"
        dest: "deploy/{{ item }}/index.html"
      loop:
        - live
        - idle
