---
- name: update HTML files from templates
  hosts: localhost
  gather_facts: true
  vars:
    current_race_name: "iRacing 12H of Sebring"
    qual_hour: 7 #integer, dont quote
    qual_min: "30" #string to keep any leading zeros, in quotes
    race_hour: 7 #integer, dont quote
    race_min: "40" #string to keep any leading zeros, in quotes
    qual_start_gmt: "{{ qual_hour }}:{{ qual_min }}"
    race_start_gmt: "{{ race_hour }}:{{ race_min }}"
    qual_start_bst: "{{ qual_hour +1 }}:{{ qual_min }}"
    race_start_bst: "{{ race_hour +1 }}:{{ race_min }}"
    matstace: true
  tasks:
    - name: template 2 versions
      template:
        src: "index_{{ item }}.html"
        dest: "deploy/{{ item }}/index.html"
      loop:
        - live
        - idle
